module.exports = {
    DATA_NOT_INFORMED: 'DATA_NOT_INFORMED',
    DATA_EXISTS: 'DATA_EXISTS',
    RECORD_SUCCESS: 'RECORD_SUCCESS',
    UPDATED_SUCCESS: 'UPDATED_SUCCESS',
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
}