module.exports = {
    DATA_NOT_INFORMED: 'DATA_NOT_INFORMED',
    DATA_EXISTS: 'DATA_EXISTS',
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    DATA_DELETED: 'DATA_DELETED',
    DATA_CONFLICT: 'DATA_CONFLICT',
    RECORD_SUCCESS: 'RECORD_SUCCESS',
    UPDATED_SUCCESS: 'UPDATED_SUCCESS',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
}